import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Logo } from './../public/img/party_haan.png';
import FormLogin from '../components/FromLogin';
import { Box, TextField } from '@mui/material';
import { motion } from 'framer-motion';
import Navbar from '../components/Navbar';
import FormCreate from '../components/FormCreate'

export default function CreateParty() {

	return (
		<div className='gradient-bg-welcome relative min-h-screen h-full w-full'>
			<Head>
				<title>Create Party</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className='gradient-bg-welcome relative w-full h-full flex flex-col px-0 justify-center items-center min-h-screen bg-[#e7544a]'>
				<div className='w-full h-full flex flex-col px-3 md:px-0 items-center justify-center'>
					<Box
						className={`${styles.BoxSigin} 
						bg-transparent border-solid border-inherit rounded-xl w-full md:w-4/12 shadow-2xl  py-5 flex flex-col justify-center items-center bg-[#ffffff] `}
					>
						<img
							src='/img/party_haan.png'
							alt=''
							className='w-12/12 h-12/12 drop-shadow-xl m-0 p-0 border-transparent'
						/>
						<FormCreate />
					</Box>
				</div>
			</main>
			{/* <div className='w-12/12 min-h-screen'></div> */}
		</div>
	);
}
