import React, {useState, useEffect} from 'react'
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Logo } from './../public/img/party_haan.png';
import FormLogin from './../components/FromLogin'
import { Box, TextField } from '@mui/material';
import { motion } from 'framer-motion';

export default function Home() {


	return (
		<div className=' gradient-bg-welcome'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='gradient-bg-welcome w-full h-full flex flex-col px-3 justify-center items-center min-h-screen bg-[#e7544a]'>
				<Box
					className={`${styles.BoxSigin} 
						bg-transparent border-solid border-inherit rounded-xl w-full md:w-4/12 shadow-2xl  py-5 flex flex-col justify-center items-center bg-[#ffffff] `}
				>
					<img
						src='/img/party_haan.png'
						alt=''
						className='w-12/12 h-12/12 drop-shadow-xl m-0 p-0 border-transparent'
					/>
					<FormLogin />
				</Box>
			</main>
		</div>
	);
}
