import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Grid, Container } from '@mui/material';
import Navbar from '../components/Navbar';
import CardParty from '../components/CardParty';
import { getParty } from '../components/api';
import Cookies from 'js-cookie';

export default function Party() {

	const [itemsParty, setItemsParty] = useState([])

	useEffect( async () => {
		try {
			let responseParty = await getParty()
			console.log(responseParty);
			if (responseParty.success == 'success') {
				setItemsParty(responseParty.message);
			}
		} catch (err) {
			console.log(err);
		}
	}, [])

	return (
		<div className='gradient-bg-welcome relative min-h-screen h-full w-full'>
			<Head>
				<title>Create Party</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<div className='gradient-bg-welcome min-h-screen h-full w-full pt-28 pb-6'>
				<Container className='w-full h-full flex flex-col justify-center items-center'>
					<Grid
						container
						spacing={{ xs: 2, md: 3 }}
						columns={{ xs: 4, sm: 8, md: 12 }}
					>
						{itemsParty.map((item, index) => (
							<Grid item xs={12} sm={4} md={4} key={index}>
								<CardParty
									className={`${styles.BoxSigin} `}
									idroomJoin={item.idroomJoin}
									partyName={item.partyName}
									content={item.content}
									typeRoom={item.typeRoom}
									people={item.people}
									quantity={item.quantity}
								/>
							</Grid>
						))}
					</Grid>
				</Container>
			</div>
		</div>
	);
}
